------------------------------------------------------------**ASSIGNMENT DAY 6**--------------------------------------
                    Assignment Submit Form : https://bit.ly/aimlassignment

**Question 1:**
Assuming that we have some email addresses in the "username@companyname.com" format, please write program
to print the company name of a given email address. Both user names and company names are composed of letters
only.
Input Format:
The first line of the input contains an email address.
Output Format:
Print the company name in single line.
Example;
Input:
john@google.com
Output:
google

**Question 2:**
Write a program that accepts a comma-separated sequence of words as input and prints the words in a comma
separated sequence after sorting them alphabetically.
Input Format:
The first line of input contains words separated by the comma.
Output Format:
Print the sorted words separated by the comma.
Example:
Input:
without,hello,bag,world
Output:
bag,hello,without,world

**Question 3:**
Create your own Jupyter Notebook for Sets.
Reference link: https://www.w3schools.com/python/python_sets.asp

**Question 4:**
Given a list of n-1 numbers ranging from 1 to n, your task is to find the missing number. There are no duplicates.
Input Format:
The first line contains n-1 numbers with each number separated by a space.
Output Format:
Print the missing number
Example:
Input:1 2 4 6 3 7 8
Output:5
Explanation:
In the above list of numbers 5 is missing and hence 5 is the input

**Question 5:**
With a given list L, write a program to print this list L after removing all duplicate values with original order reserved.
Example:
If the input list is
12 24 35 24 88 120 155 88 120 155
Then the output should be
12 24 35 88 120 155
Explanation:
Third, seventh and ninth element of the list L has been removed because it was already present.
Input Format:
In one line take the elements of the list L with each element separated by a space.
Output Format:
Print the elements of the modified list in one line with each element separated by a space.
Example:
Input: 12 24 35 24
Output:
12 24 35

**Question 1:**
Assuming that we have some email addresses in the "username@companyname.com" format, please write program
to print the company name of a given email address. Both user names and company names are composed of letters
only.
Input Format:
The first line of the input contains an email address.
Output Format:
Print the company name in single line.
Example;
Input:
john@google.com
Output:
google

In [6]:
# ANSWER 1:

e = input("Enter the Email address: ", )
start = e.find('@') + 1
end = e.find('.', start)
c_name = e[start:end]
print("Entered email address belongs to:", c_name.upper())

Enter the Email address: abhitiwari09@microsoft.com
Entered email address belongs to: MICROSOFT

**Question 2:**
Write a program that accepts a comma-separated sequence of words as input and prints the words in a comma
separated sequence after sorting them alphabetically.
Input Format:
The first line of input contains words separated by the comma.
Output Format:
Print the sorted words separated by the comma.
Example:
Input:
without,hello,bag,world
Output:
bag,hello,without,world

In [22]:
# ANSWER 2:

li = [str(x) for x in input("Enter multiple inputs: ").split(",")]
L = li.sort()
print(li)

Enter multiple inputs: true,i,say
['i', 'say', 'true']

## Question 3 is answered after answer to question 5

**QUESTION 4:**
Given a list of n-1 numbers ranging from 1 to n, your task is to find the missing number. There are no duplicates.
Input Format:
The first line contains n-1 numbers with each number separated by a space.
Output Format:
Print the missing number
Example:
Input:1 2 4 6 3 7 8
Output:5
Explanation:
In the above list of numbers 5 is missing and hence 5 is the input

In [43]:
L = [1,2,3,5,6,8,9,11]  #given list
L.sort()
print(L)
l = int(len(L)) #length of given list
ml=[] #missing list
for i in range(L[0],L[l-1]):
    if i not in L:
        ml.append(i)
        
print("List of numbers missing is:",ml)

[1, 2, 3, 5, 6, 8, 9, 11]
List of numbers missing is: [4, 7, 10]

**QUESTION 5:**
With a given list L, write a program to print this list L after removing all duplicate values with original order reserved.
Example:
If the input list is
12 24 35 24 88 120 155 88 120 155
Then the output should be
12 24 35 88 120 155
Explanation:
Third, seventh and ninth element of the list L has been removed because it was already present.
Input Format:
In one line take the elements of the list L with each element separated by a space.
Output Format:
Print the elements of the modified list in one line with each element separated by a space.
Example:
Input: 12 24 35 24
Output:
12 24 35

In [48]:
# ANSWER 5

L = [5,10,15,5,20,25,15,25,30]
L.sort()
print("Input list is:",L)
print("\n")

#removing duplicates using Dictionary
nl_dict= list(dict.fromkeys(L))
print("List after removing duplicates using Dictionary is:",nl)
print("\n")

#removing duplicates using Set Method
nl_set= list(set(L))
print("List after removing duplicates using Set Method is:",nl)

Input list is: [5, 5, 10, 15, 15, 20, 25, 25, 30]


List after removing duplicates using Dictionary is: [5, 10, 15, 20, 25, 30]


List after removing duplicates using Set Method is: [5, 10, 15, 20, 25, 30]

**QUESTION 3:**
Create your own Jupyter Notebook for Sets.
Reference link: https://www.w3schools.com/python/python_sets.asp

**JUPYTER NOTEBOOK FOR SETS:**

a) **Set:** A set is a collection of distinct objects and is unordered and unindexed. In Python, sets are written with curly brackets.

<p>
Example: Create a Set: 
<br>Example_set = {"apple", "banana", "cherry"} 
<br>print(Example_set)
<p/>

OUTPUT:
<br>{'apple', 'banana', 'cherry'}

b) **Access Items in a Set:** You cannot access items in a set by referring to an index, since sets are unordered the items has no index. But you can *loop through the set items using a for loop*, or ask if a specified value is present in a set, by using the *in* keyword.

Example:

     Loop through the set, and print the values:
     thisset = {"apple", "banana", "cherry"}
     for x in thisset:
     print(x) 

     OUTPUT:
     apple
     banana
     cherry

Example: Check if "banana" is present in the set: 
<br>thisset = {"apple", "banana", "cherry"} 
<br>print("banana" in thisset)

   OUTPUT:
   True
c) **Change Items in a Set:** 
Once a set is created, you cannot change its items, but you can add new items.

Add Items: To add one item to a set use the add() method. To add more than one item to a set use the update() method.

<br>Example: Add an item to a set, using the add() method: 
<br>thisset = {"apple", "banana", "cherry"} 
<br>thisset.add("orange") 
<br>print(thisset)

   OUTPUT:
   {'apple', 'orange', 'banana', 'cherry'}

Example: Add multiple items to a set, using the update() method: 
<br>thisset = {"apple", "banana", "cherry"} 
<br>thisset.update(["orange", "mango", "grapes"]) 
<br>print(thisset)

  OUTPUT:
  {'grapes', 'cherry', 'orange', 'banana', 'mango', 'apple'}

d) **Get the Length of a Set:** 
To determine how many items a set has, use the len() method. 
<br>Example: Get the number of items in a set: 
<br>thisset = {"apple", "banana", "cherry"} 
<br>print(len(thisset))

OUTPUT: 3

e) **Remove Item in a SET:** 
To remove an item in a set, use the *remove(), or the discard() method*. 
<br>Example: Remove "banana" by using the remove() method: 
<br>thisset = {"apple", "banana", "cherry"} 
<br>thisset.remove("banana") 
<br>print(thisset)

  OUTPUT:
  {'apple', 'cherry'}

  You can also use the *pop() method to remove an item*, but this method will remove the last item. Remember that sets are unordered, so you will not know what item that gets removed.
  
  **The return value of the pop() method is the removed item.**
  
Example: Remove the last item by using the pop() method: 
<br>thisset = {"apple", "banana", "cherry"} 
<br>x = thisset.pop() 
<br>print(x) 
<br>print(thisset)

  OUTPUT:
  apple
 {'banana', 'cherry'}

 The clear() method empties the set:
<br> thisset = {"apple", "banana", "cherry"}
<br> thisset.clear()
<br> print(thisset) 

 OUTPUT:
 set()
Example: The del keyword will delete the set completely: 
<br>thisset = {"apple", "banana", "cherry"} 
<br>del thisset 
<br>print(thisset)

 OUTPUT:
 set()
 
g) **Join Two Sets:** There are several ways to join two or more sets in Python. You can use the union() method that returns a new set containing all items from both sets, or the update() method that inserts all the items from one set into another: 
Example: The union() method returns a new set with all items from both sets: 
<br>set1 = {"a", "b" , "c"} 
<br>set2 = {1, 2, 3} 
<br>set3 = set1.union(set2) 
<br>print(set3)

 OUTPUT:
 {1, 2, 'a', 'b', 3, 'c'}

Example: The update() method inserts the items in set2 into set1: 
<br>set1 = {"a", "b" , "c"} 
<br>set2 = {1, 2, 3} 
<br>set1.update(set2) 
<br>print(set1)

  OUTPUT:
 {1, 2, 'a', 'b', 3, 'c'}
 
h) **The set() Constructor:** It is also possible to use the *set() constructor to make a set*. 
<br>Example: Using the set() constructor to make a set: 
<br>thisset = set(("apple", "banana", "cherry")) # note the double round-brackets print(thisset)

OUTPUT: {'apple', 'banana', 'cherry'}

i) **Set Methods:** Apart from all the above instructions,Python has many more set of built-in methods that you can use in sets.

<br>*add()*:Adds an element to the set 
<br>*clear()*:Removes all the elements from the set 
<br>*copy()*:Returns a copy of the set 
<br>*difference()*:Returns a set containing the difference between two or more sets 
<br>*difference_update()*:Removes the items in this set that are also included in another, specified set 
<br>*discard()*:Remove the specified item intersection():Returns a set, that is the intersection of two other sets <br>*intersection_update*():Removes the items in this set that are not present in other, specified set(s) <br>*isdisjoint()*:Returns whether two sets have a intersection or not 
<br>*issubset()*:Returns whether another set contains this set or not 
<br>*issuperset()*:Returns whether this set contains another set or not 
<br>*pop()*:Removes an element from the set remove():Removes the specified element